[theme]
theme = "gruvbox-dark"
[theme.overrides]
separator = ""

[icons]
icons = "material-nf"


#

[[block]]
block = "music"
format = """ \
    <span size='13pt' rise='-3pt' color='grey'>$icon</span> \
    $combo.str(min_w:0, max_w:75) | \
"""

[[block]]
block = "net"
format = """ \
    <span size='24pt' rise='-4pt' color='grey'>$icon</span> \
    <span background='green'> [$ssid] </span> \
    <span letter_spacing='-1024'>$ip</span> \
    <span color='yellow' letter_spacing='-512'> $speed_down.eng(prefix:K) ⇵ $speed_up.eng(prefix:K)</span> \
"""
[[block.click]]
button = "left"
cmd = "iwgtk"


[[block]]
block = "backlight"
device = "nv_backlight"
format = """ \
    <span size='25pt' letter_spacing="-512" rise='-2pt' color='cyan'>$icon</span> \
    <span rise='4pt'>$brightness</span> \
"""


[[block]]
block = "sound"
driver = "pulseaudio"
max_vol = 150
step_width = 3
show_volume_when_muted = true
format = """ \
    <span size='24pt' rise='-5pt' color='cyan'>$icon</span> \
    <span rise='6pt'>$volume</span> \
"""
[[block.click]]
button = "left"
cmd = "env WAYLAND_DISPLAY=wayland-0 newspawn pavucontrol"
[block.icons_overrides]
volume_muted = "<span size='36pt' rise='-3pt'>󰝟</span>"


[[block]]
block = "battery"
driver = "sysfs"
format = """ \
    <span size='20pt' rise='-2pt'>$icon</span> \
    <span size='20pt' rise='-3pt'>$percentage $time</span> \
"""
missing_format = " <span size='25pt' rise='-2pt'>$icon</span> "


[[block]]
block = "cpu"
interval = 1
format = """ \
    <span size='25pt' color='cyan' rise='-4pt'>$icon</span> \
    $frequency \
"""

[[block]]
block = "cpu"
interval = 1
format = """ \
    <span size='13pt' letter_spacing='-1024' rise='-6pt' color='cyan' >\
    $utilization1.bar(w:6,max_value:100)$utilization2.bar(w:6,max_value:100)$utilization3.bar(w:6,max_value:100)$utilization4.bar(w:6,max_value:100)\
    </span>\
"""


[[block]]
block = "temperature"
interval = 2
chip = "*-isa-*"
format = " $min ~$max<span rise='5pt'>max</span> "

[[block]]
block = "temperature"
interval = 2
chip = "*-pci-*"
format = " $average<span rise='5pt'>gpu</span> "


[[block]]
block = "memory"
format = """ \
    <span size='25pt' color='yellow' rise='-5pt'>$icon</span> \
    $mem_total_used \
    <span size='90%' rise='2pt'>⇄ </span>$swap_used \
"""
format_alt = """ \
    <span size='25pt' color='yellow' rise='-5pt'>$icon</span> \
    (swap: $swap_used/$swap_total, buf: $buffers, cache: $cached) \
"""


[[block]]
path = "/"
block = "disk_space"
format = " <span color='yellow' rise='2pt'>/</span>$available "
[[block.click]]
button = "left"
cmd = 'newspawn krusader --right $HOME --left $(fd . /run/media/$USER -d 1 | read && echo "/run/media/$USER" || echo "/")'

[[block]]
path = "~/"
block = "disk_space"
format = " <span color='yellow' rise='2pt'>~/</span> $available "
[[block.click]]
button = "left"
cmd = "newspawn krusader --right $HOME --left $HOME"


[[block]]
block = "uptime"
format = " <span size='28pt' color='skyblue' rise='-5pt'>󱫣</span> <u>$text</u> "



[[block]]
block = "pacman"
signal = 1
interval = 600
format = " <span size='22pt' rise='-4pt'>$icon</span> $aur "
format_singular = " $aur "
format_up_to_date = " <span size='22pt' rise='-5pt'>$icon</span> "
critical_updates_regex = "(linux|linux-lts|)"
aur_command = "paru -Qu"
[[block.click]]
button = "left"
cmd = "newspawn alacritty -e nvim term://'sudo pacman -Syu && paru -Syu' --cmd 'au TermOpen * ++once normal a'"



[[block]]
block = "keyboard_layout"
driver = "sway"
format = "  <span size='20pt'>$layout</span> "
[block.mappings]
"English (US)" = "🇺🇸"
"Russian (N/A)" = "🇷🇺"
"Polish (N/A)" = "🇵🇱"
"Ukrainian (N/A)" = "🇺🇦"
