[theme]
theme = "gruvbox-dark"
[theme.overrides]
separator = ""

[icons]
icons = "material-nf"


#

[[block]]
block = "music"
format = """ \
    <span font_size='13pt' baseline_shift='-3pt' color='grey'>$icon</span> \
    $combo.str(min_w:0, max_w:75) | \
"""

[[block]]
block = "net"
format = """ \
    <span font_size='24pt' baseline_shift='-4pt' color='grey'>$icon</span> \
    <span background='green'> [$ssid] </span> \
    <span letter_spacing='-1024'>$ip</span> \
    <span color='yellow' letter_spacing='-512'> $speed_down.eng(prefix:K) ⇵ $speed_up.eng(prefix:K)</span> \
"""
[[block.click]]
button = "left"
cmd = "iwgtk"


[[block]]
block = "backlight"
device = "nv_backlight"
format = """ \
    <span font_size='25pt' letter_spacing="-512" baseline_shift='-2pt' color='cyan'>$icon</span> \
    <span baseline_shift='4pt'>$brightness</span> \
"""


[[block]]
block = "sound"
driver = "pulseaudio"
max_vol = 150
step_width = 3
show_volume_when_muted = true
format = """ \
    <span font_size='24pt' baseline_shift='-3pt' color='cyan'>$icon</span> \
    <span baseline_shift='6pt'>$volume</span> \
"""
[[block.click]]
button = "left"
cmd = "env WAYLAND_DISPLAY=wayland-0 newspawn pavucontrol"
[block.icons_overrides]
volume_muted = "<span font_size='36pt'>󰝟</span>"


[[block]]
block = "battery"
driver = "sysfs"
format = """ \
    <span font_size='20pt' baseline_shift='-2pt'>$icon</span> \
    <span font_size='20pt' baseline_shift='-3pt'>$percentage $time</span> \
"""
missing_format = " <span font_size='25pt' baseline_shift='-2pt'>$icon</span> "


[[block]]
block = "cpu"
interval = 1
format = """ \
    <span font_size='25pt' color='cyan' baseline_shift='-4pt'>$icon</span> \
    $frequency \
"""

[[block]]
block = "cpu"
interval = 1
format = """ \
    <span font_size='13pt' letter_spacing='-1024' baseline_shift='-6pt' color='cyan' >\
    $utilization1.bar(w:6,max_value:100)$utilization2.bar(w:6,max_value:100)$utilization3.bar(w:6,max_value:100)$utilization4.bar(w:6,max_value:100)\
    </span>\
"""


[[block]]
block = "temperature"
interval = 2
chip = "*-isa-*"
format = " $min ~$max<span baseline_shift='superscript'>max</span> "

[[block]]
block = "temperature"
interval = 2
chip = "*-pci-*"
format = " $average<span baseline_shift='superscript'>gpu</span> "


[[block]]
block = "memory"
format = """ \
    <span font_size='25pt' color='yellow' baseline_shift='-5pt'>$icon</span> \
    $mem_total_used \
    <span font_size='90%' baseline_shift='2pt'>⇄ </span>$swap_used \
"""
format_alt = """ \
    <span font_size='25pt' color='yellow' baseline_shift='-5pt'>$icon</span> \
    (swap: $swap_used/$swap_total, buf: $buffers, cache: $cached) \
"""


[[block]]
path = "/"
block = "disk_space"
format = "$icon <span color='yellow'>/</span>$available "
icons_format = ""
[[block.click]]
button = "left"
cmd = 'newspawn krusader --right $HOME --left $(fd . /run/media/$USER -d 1 | read && echo "/run/media/$USER" || echo "/")'

[[block]]
path = "~/"
block = "disk_space"
format = "$icon <span color='yellow'>~</span>$available "
icons_format = ""
[[block.click]]
button = "left"
cmd = "newspawn krusader --right $HOME --left $HOME"


[[block]]
block = "uptime"
format = "<span font_size='25pt' color='skyblue' baseline_shift='-5pt'>$icon</span> $text "



[[block]]
block = "pacman"
signal = 1
interval = 600
format = """ \
    <span font_size='22pt' baseline_shift='-4pt'>$icon</span> \
    $pacman + $aur(AUR) = $both \
"""
format_singular = " $both "
format_up_to_date = " <span font_size='22pt' baseline_shift='-4pt'>$icon</span> "
critical_updates_regex = "(linux|linux-lts|)"
aur_command = "paru -Qua"
[[block.click]]
button = "left"
cmd = "newspawn alacritty -e nvim term://'sudo pacman -Syu && paru -Syu' --cmd 'au TermOpen * ++once normal a'"



[[block]]
block = "keyboard_layout"
driver = "sway"
format = " <span font_size='20pt'>$layout</span> "
[block.mappings]
"English (US)" = "🇺🇸"
"Russian (N/A)" = "🇷🇺"
"Polish (N/A)" = "🇵🇱"
"Ukrainian (N/A)" = "🇺🇦"
